"""empty message

Revision ID: 07a48ca4b362
Revises: 1aae715e7889
Create Date: 2019-10-05 06:58:54.453064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07a48ca4b362'
down_revision = '1aae715e7889'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_type', sa.String(length=10), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('customer_no', sa.String(length=50), nullable=True),
    sa.Column('child_policy', sa.Integer(), nullable=True),
    sa.Column('date_due', sa.DateTime(), nullable=True),
    sa.Column('date_paid', sa.DateTime(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['child_policy'], ['child_policy.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('child_policy', sa.Column('reason', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('child_policy', 'reason')
    op.drop_table('policy_transactions')
    # ### end Alembic commands ###
