"""empty message

Revision ID: 16452567fc42
Revises: 1d27f5bacd78
Create Date: 2019-10-13 12:40:15.809738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16452567fc42'
down_revision = '1d27f5bacd78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('policy_payments', 'is_paid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policy_payments', sa.Column('is_paid', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
