"""empty message

Revision ID: 16cf90bf870b
Revises: 2dd4a7f9bd34
Create Date: 2019-08-05 16:39:39.208008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16cf90bf870b'
down_revision = '2dd4a7f9bd34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('br_customer', sa.Column('status', sa.Boolean(), nullable=True))
    op.drop_column('br_customer', 'is_active')
    op.add_column('ia_customer', sa.Column('status', sa.Boolean(), nullable=True))
    op.drop_column('ia_customer', 'is_active')
    op.add_column('ta_customer', sa.Column('status', sa.Boolean(), nullable=True))
    op.drop_column('ta_customer', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ta_customer', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('ta_customer', 'status')
    op.add_column('ia_customer', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('ia_customer', 'status')
    op.add_column('br_customer', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('br_customer', 'status')
    # ### end Alembic commands ###
