"""empty message

Revision ID: 1995e9d6953d
Revises: 598718920c82
Create Date: 2019-08-29 12:50:36.910818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1995e9d6953d'
down_revision = '598718920c82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licence_classes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company', sa.Integer(), nullable=True),
    sa.Column('insurance_class', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company'], ['company_details.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['insurance_class'], ['insurance_class.class_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('licenced_classes')
    op.add_column('insurance_company', sa.Column('associated_company', sa.Integer(), nullable=True))
    op.drop_constraint('insurance_company_company_details_fkey', 'insurance_company', type_='foreignkey')
    op.create_foreign_key(None, 'insurance_company', 'company_details', ['associated_company'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('insurance_company', 'company_details')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insurance_company', sa.Column('company_details', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'insurance_company', type_='foreignkey')
    op.create_foreign_key('insurance_company_company_details_fkey', 'insurance_company', 'company_details', ['company_details'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('insurance_company', 'associated_company')
    op.create_table('licenced_classes',
    sa.Column('company', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('class', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['class'], ['insurance_class.class_id'], name='licenced_classes_class_fkey'),
    sa.ForeignKeyConstraint(['company'], ['company_details.id'], name='licenced_classes_company_fkey')
    )
    op.drop_table('licence_classes')
    # ### end Alembic commands ###
