"""empty message

Revision ID: 1caffdedc70c
Revises: 186105435e7b
Create Date: 2019-09-23 11:12:36.628100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1caffdedc70c'
down_revision = '186105435e7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('country', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'country')
    # ### end Alembic commands ###
