"""empty message

Revision ID: 1d27f5bacd78
Revises: 2265af020081
Create Date: 2019-10-11 12:44:01.088687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1d27f5bacd78'
down_revision = '2265af020081'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_type', sa.String(length=10), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('customer_no', sa.String(length=50), nullable=True),
    sa.Column('child_policy_id', sa.Integer(), nullable=True),
    sa.Column('next_date', sa.DateTime(), nullable=True),
    sa.Column('amount_due', sa.Float(), nullable=False),
    sa.Column('transaction_code', sa.String(length=25), nullable=True),
    sa.Column('date_paid', sa.DateTime(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['child_policy_id'], ['child_policy.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('policy_transactions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('customer_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('child_policy', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_paid', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_paid', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('amount_due', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=25), autoincrement=False, nullable=True),
    sa.Column('next_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['child_policy'], ['child_policy.id'], name='policy_transactions_child_policy_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='policy_transactions_pkey')
    )
    op.drop_table('policy_payments')
    # ### end Alembic commands ###
