"""empty message

Revision ID: 2265af020081
Revises: c3b807a70586
Create Date: 2019-10-09 13:01:34.342512

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2265af020081'
down_revision = 'c3b807a70586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policy_transactions', sa.Column('amount_due', sa.Float(), nullable=False))
    op.add_column('policy_transactions', sa.Column('key', sa.String(length=25), nullable=True))
    op.add_column('policy_transactions', sa.Column('next_date', sa.DateTime(), nullable=True))
    op.drop_column('policy_transactions', 'date_due')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policy_transactions', sa.Column('date_due', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('policy_transactions', 'next_date')
    op.drop_column('policy_transactions', 'key')
    op.drop_column('policy_transactions', 'amount_due')
    # ### end Alembic commands ###
