"""empty message

Revision ID: 26892502c566
Revises: ee7339d2f879
Create Date: 2019-09-10 16:41:30.344899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26892502c566'
down_revision = 'ee7339d2f879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ic_extension', sa.Column('insurance_company_id', sa.Integer(), nullable=True))
    op.drop_constraint('ic_extension_insurance_company_fkey', 'ic_extension', type_='foreignkey')
    op.create_foreign_key(None, 'ic_extension', 'insurance_company', ['insurance_company_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('ic_extension', 'insurance_company')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ic_extension', sa.Column('insurance_company', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ic_extension', type_='foreignkey')
    op.create_foreign_key('ic_extension_insurance_company_fkey', 'ic_extension', 'insurance_company', ['insurance_company'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('ic_extension', 'insurance_company_id')
    # ### end Alembic commands ###
