"""empty message

Revision ID: 26e7cd51eb66
Revises: 1caffdedc70c
Create Date: 2019-09-23 11:38:48.987547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26e7cd51eb66'
down_revision = '1caffdedc70c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ic_loadings', sa.Column('insurance_company_id', sa.Integer(), nullable=True))
    op.drop_constraint('ic_loadings_insurance_company_fkey', 'ic_loadings', type_='foreignkey')
    op.create_foreign_key(None, 'ic_loadings', 'insurance_company', ['insurance_company_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('ic_loadings', 'insurance_company')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ic_loadings', sa.Column('insurance_company', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ic_loadings', type_='foreignkey')
    op.create_foreign_key('ic_loadings_insurance_company_fkey', 'ic_loadings', 'insurance_company', ['insurance_company'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('ic_loadings', 'insurance_company_id')
    # ### end Alembic commands ###
