"""Updated master policy model, changed 'status' field to 'active'

Revision ID: 27bbbf7b79e8
Revises: da4dccdf63ea
Create Date: 2019-09-04 15:23:52.468920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27bbbf7b79e8'
down_revision = 'da4dccdf63ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_policy', sa.Column('active', sa.Boolean(), nullable=False))
    op.drop_column('master_policy', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_policy', sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('master_policy', 'active')
    # ### end Alembic commands ###
