"""empty message

Revision ID: 27d4ff9a2567
Revises: 07a48ca4b362
Create Date: 2019-10-07 12:24:15.912918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27d4ff9a2567'
down_revision = '07a48ca4b362'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('child_policy_cp_number_key', 'child_policy', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('child_policy_cp_number_key', 'child_policy', ['cp_number'])
    # ### end Alembic commands ###
