"""empty message

Revision ID: 2b3012611279
Revises: fc5213b3d896
Create Date: 2019-08-22 14:09:58.988197

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2b3012611279'
down_revision = 'fc5213b3d896'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('levies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ic_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company', sa.Integer(), nullable=True),
    sa.Column('insurance_class', sa.Integer(), nullable=True),
    sa.Column('sub_class', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company'], ['insurance_company.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['insurance_class'], ['insurance_class.class_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sub_class'], ['insurance_subclass.class_code'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle_modifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('accessory_name', sa.String(length=200), nullable=True),
    sa.Column('make', sa.String(length=100), nullable=True),
    sa.Column('estimated_value', sa.Float(), nullable=True),
    sa.Column('serial_no', sa.String(length=200), nullable=True),
    sa.Column('vehicle', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle'], ['vehicle_details.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('child_policy', sa.Column('date_registered', sa.DateTime(), nullable=True))
    op.drop_column('child_policy', 'date_created')
    op.add_column('master_policy', sa.Column('company', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'master_policy', 'insurance_company', ['company'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('vehicle_details', sa.Column('engine_capacity', sa.Integer(), nullable=False))
    op.add_column('vehicle_details', sa.Column('manufacture_year', sa.Integer(), nullable=False))
    op.add_column('vehicle_details', sa.Column('no_of_seats', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_details', 'no_of_seats')
    op.drop_column('vehicle_details', 'manufacture_year')
    op.drop_column('vehicle_details', 'engine_capacity')
    op.drop_constraint(None, 'master_policy', type_='foreignkey')
    op.drop_column('master_policy', 'company')
    op.add_column('child_policy', sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('child_policy', 'date_registered')
    op.drop_table('vehicle_modifications')
    op.drop_table('ic_products')
    op.drop_table('levies')
    # ### end Alembic commands ###
