"""empty message

Revision ID: 2c0afe941463
Revises: 49e409e2794d
Create Date: 2019-09-21 06:51:49.594594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c0afe941463'
down_revision = '49e409e2794d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insurance_company', sa.Column('company_details', sa.Integer(), nullable=True))
    op.drop_constraint('insurance_company_associated_company_fkey', 'insurance_company', type_='foreignkey')
    op.create_foreign_key(None, 'insurance_company', 'company_details', ['company_details'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('insurance_company', 'associated_company')
    op.drop_column('user_profile', 'country')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('country', sa.VARCHAR(length=3), autoincrement=False, nullable=True))
    op.add_column('insurance_company', sa.Column('associated_company', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'insurance_company', type_='foreignkey')
    op.create_foreign_key('insurance_company_associated_company_fkey', 'insurance_company', 'company_details', ['associated_company'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('insurance_company', 'company_details')
    # ### end Alembic commands ###
