"""Updated the licensed classes model

Revision ID: 2c1a84553120
Revises: 50f03fbd58b9
Create Date: 2019-09-03 11:44:26.724780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c1a84553120'
down_revision = '50f03fbd58b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licenced_classes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company', sa.Integer(), nullable=True),
    sa.Column('insurance_class', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company'], ['company_details.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['insurance_class'], ['insurance_class.class_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('licence_classes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licence_classes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('insurance_class', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company'], ['company_details.id'], name='licence_classes_company_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['insurance_class'], ['insurance_class.class_id'], name='licence_classes_insurance_class_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='licence_classes_pkey')
    )
    op.drop_table('licenced_classes')
    # ### end Alembic commands ###
