"""empty message

Revision ID: 32f83bfc77bb
Revises: 9b9374ba6fba
Create Date: 2019-08-28 14:10:27.297647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32f83bfc77bb'
down_revision = '9b9374ba6fba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licenced_classes',
    sa.Column('company', sa.Integer(), nullable=True),
    sa.Column('class', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class'], ['insurance_class.class_id'], ),
    sa.ForeignKeyConstraint(['company'], ['company_details.id'], )
    )
    op.create_table('policy_benefits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=True),
    sa.Column('ic_benefit', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ic_benefit'], ['ic_benefit.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['child_policy.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('policy_benefits')
    op.drop_table('licenced_classes')
    # ### end Alembic commands ###
