"""empty message

Revision ID: 429f680397bb
Revises: fb10c3dde23e
Create Date: 2019-08-28 16:28:12.252117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '429f680397bb'
down_revision = 'fb10c3dde23e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('master_policy_company_fkey', 'master_policy', type_='foreignkey')
    op.create_foreign_key(None, 'master_policy', 'company_details', ['company'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'master_policy', type_='foreignkey')
    op.create_foreign_key('master_policy_company_fkey', 'master_policy', 'insurance_company', ['company'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
