"""Child policy

Revision ID: 442778516ece
Revises: 
Create Date: 2019-08-16 16:35:49.232660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '442778516ece'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benefit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('class_code', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_code'], ['insurance_class.class_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('child_policy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle', sa.Integer(), nullable=True),
    sa.Column('customer_number', sa.String(length=50), nullable=True),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_expiry', sa.DateTime(), nullable=True),
    sa.Column('premium_amount', sa.Float(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.Column('agency_role', sa.Integer(), nullable=True),
    sa.Column('master_policy', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agency_role'], ['role.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['master_policy'], ['master_policy.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle'], ['vehicle_details.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extension',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('class_code', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_code'], ['insurance_class.class_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ic_benefit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('insurance_company', sa.Integer(), nullable=True),
    sa.Column('benefit', sa.Integer(), nullable=True),
    sa.Column('free_limit', sa.Float(), nullable=False),
    sa.Column('max_limit', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['benefit'], ['benefit.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['insurance_company'], ['insurance_company.company_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ic_extension',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('insurance_company', sa.Integer(), nullable=True),
    sa.Column('extension', sa.Integer(), nullable=True),
    sa.Column('free_limit', sa.Float(), nullable=False),
    sa.Column('max_limit', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['extension'], ['extension.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['insurance_company'], ['insurance_company.company_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ic_loadings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('insurance_company', sa.Integer(), nullable=True),
    sa.Column('loading', sa.Integer(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['insurance_company'], ['insurance_company.company_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['loading'], ['loading.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loading',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('master_policy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mp_number', sa.String(length=22), nullable=False),
    sa.Column('customer', sa.String(length=22), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_expiry', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mp_number')
    )
    op.create_table('policy_benefits',
    sa.Column('policy_id', sa.Integer(), nullable=True),
    sa.Column('ic_benefit_id', sa.Integer(), nullable=True),
    sa.Column('limit', sa.Float(), nullable=False),
    sa.Column('premium', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ic_benefit_id'], ['ic_benefit.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['child_policy.id'], )
    )
    op.create_table('policy_extensions',
    sa.Column('policy_id', sa.Integer(), nullable=True),
    sa.Column('ic_extension_id', sa.Integer(), nullable=True),
    sa.Column('limit', sa.Float(), nullable=False),
    sa.Column('premium', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ic_extension_id'], ['ic_extension.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['child_policy.id'], )
    )
    op.create_table('vehicle_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reg_number', sa.String(length=8), nullable=True),
    sa.Column('model', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('body_type', sa.String(length=20), nullable=True),
    sa.Column('origin', sa.String(length=20), nullable=True),
    sa.Column('sum_insured', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['model'], ['car_model.model_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['child_policy.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('insurance_company', sa.Column('company_id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('insurance_company', 'insurance_company_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insurance_company', sa.Column('insurance_company_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('insurance_company', 'company_id')
    op.drop_table('vehicle_details')
    op.drop_table('policy_extensions')
    op.drop_table('policy_benefits')
    op.drop_table('master_policy')
    op.drop_table('loading')
    op.drop_table('ic_loadings')
    op.drop_table('ic_extension')
    op.drop_table('ic_benefit')
    op.drop_table('extension')
    op.drop_table('child_policy')
    op.drop_table('benefit')
    # ### end Alembic commands ###
