"""empty message

Revision ID: 49e409e2794d
Revises: e641468fbab4
Create Date: 2019-09-19 11:13:56.721922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49e409e2794d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('constituency', sa.Column('county_id', sa.Integer(), nullable=True))
    op.drop_constraint('constituency_county_fkey', 'constituency', type_='foreignkey')
    op.create_foreign_key(None, 'constituency', 'county', ['county_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('constituency', 'county')
    op.add_column('ward', sa.Column('constituency_id', sa.Integer(), nullable=True))
    op.add_column('ward', sa.Column('county_id', sa.Integer(), nullable=True))
    op.drop_constraint('ward_county_fkey', 'ward', type_='foreignkey')
    op.drop_constraint('ward_constituency_fkey', 'ward', type_='foreignkey')
    op.create_foreign_key(None, 'ward', 'constituency', ['constituency_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'ward', 'county', ['county_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('ward', 'constituency')
    op.drop_column('ward', 'county')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ward', sa.Column('county', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ward', sa.Column('constituency', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ward', type_='foreignkey')
    op.drop_constraint(None, 'ward', type_='foreignkey')
    op.create_foreign_key('ward_constituency_fkey', 'ward', 'constituency', ['constituency'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('ward_county_fkey', 'ward', 'county', ['county'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('ward', 'county_id')
    op.drop_column('ward', 'constituency_id')
    op.add_column('constituency', sa.Column('county', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'constituency', type_='foreignkey')
    op.create_foreign_key('constituency_county_fkey', 'constituency', 'county', ['county'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('constituency', 'county_id')
    # ### end Alembic commands ###
