"""empty message

Revision ID: 4fe3abff50a6
Revises: 1b4478ad464d
Create Date: 2019-08-29 13:21:31.211271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fe3abff50a6'
down_revision = '1b4478ad464d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('make_origin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make_origin', sa.String(length=100), nullable=False),
    sa.Column('relativity', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('make_origin')
    # ### end Alembic commands ###
