"""empty message

Revision ID: 5554722a05c3
Revises: 16452567fc42
Create Date: 2019-12-04 15:37:17.456330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5554722a05c3'
down_revision = '16452567fc42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'broker', ['avatar_url'])
    op.create_unique_constraint(None, 'independent_agent', ['avatar_url'])
    op.create_unique_constraint(None, 'user_profile', ['avatar_url'])
    op.add_column('vehicle_details', sa.Column('logbook_file', sa.String(length=150), nullable=True))
    op.add_column('vehicle_details', sa.Column('national_id_file', sa.String(length=150), nullable=True))
    op.create_unique_constraint(None, 'vehicle_details', ['logbook_file'])
    op.create_unique_constraint(None, 'vehicle_details', ['national_id_file'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicle_details', type_='unique')
    op.drop_constraint(None, 'vehicle_details', type_='unique')
    op.drop_column('vehicle_details', 'national_id_file')
    op.drop_column('vehicle_details', 'logbook_file')
    op.drop_constraint(None, 'user_profile', type_='unique')
    op.drop_constraint(None, 'independent_agent', type_='unique')
    op.drop_constraint(None, 'broker', type_='unique')
    # ### end Alembic commands ###
