"""empty message

Revision ID: 598718920c82
Revises: 97ff51464049
Create Date: 2019-08-29 12:15:04.422149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '598718920c82'
down_revision = '97ff51464049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('age_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data', sa.Integer(), nullable=False),
    sa.Column('lower_limit', sa.Integer(), nullable=False),
    sa.Column('upper_limit', sa.Integer(), nullable=False),
    sa.Column('relativity', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('age_data')
    # ### end Alembic commands ###
