"""empty message

Revision ID: 5db66bf574ed
Revises: 
Create Date: 2019-09-12 19:27:41.019437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5db66bf574ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ic_rate_discount',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rates', sa.String(length=20), nullable=False),
    sa.Column('ic_company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ic_company_id'], ['insurance_company.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ic_benefit', sa.Column('benefit_id', sa.Integer(), nullable=True))
    op.add_column('ic_benefit', sa.Column('insurance_company_id', sa.Integer(), nullable=True))
    op.drop_constraint('ic_benefit_benefit_fkey', 'ic_benefit', type_='foreignkey')
    op.drop_constraint('ic_benefit_insurance_company_fkey', 'ic_benefit', type_='foreignkey')
    op.create_foreign_key(None, 'ic_benefit', 'benefit', ['benefit_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'ic_benefit', 'insurance_company', ['insurance_company_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('ic_benefit', 'insurance_company')
    op.drop_column('ic_benefit', 'benefit')
    op.add_column('ic_extension', sa.Column('extension_id', sa.Integer(), nullable=True))
    op.add_column('ic_extension', sa.Column('insurance_company_id', sa.Integer(), nullable=True))
    op.drop_constraint('ic_extension_extension_fkey', 'ic_extension', type_='foreignkey')
    op.drop_constraint('ic_extension_insurance_company_fkey', 'ic_extension', type_='foreignkey')
    op.create_foreign_key(None, 'ic_extension', 'extension', ['extension_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'ic_extension', 'insurance_company', ['insurance_company_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('ic_extension', 'insurance_company')
    op.drop_column('ic_extension', 'extension')
    op.drop_constraint('master_policy_company_fkey', 'master_policy', type_='foreignkey')
    op.create_foreign_key(None, 'master_policy', 'insurance_company', ['company'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('policy_benefits', sa.Column('ic_benefit_id', sa.Integer(), nullable=True))
    op.drop_constraint('policy_benefits_ic_benefit_fkey', 'policy_benefits', type_='foreignkey')
    op.create_foreign_key(None, 'policy_benefits', 'ic_benefit', ['ic_benefit_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('policy_benefits', 'ic_benefit')
    op.add_column('policy_extension', sa.Column('ic_extension_id', sa.Integer(), nullable=True))
    op.drop_constraint('policy_extension_ic_extension_fkey', 'policy_extension', type_='foreignkey')
    op.create_foreign_key(None, 'policy_extension', 'ic_extension', ['ic_extension_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('policy_extension', 'ic_extension')
    op.add_column('vehicle_details', sa.Column('driver_id', sa.Integer(), nullable=True))
    op.drop_constraint('vehicle_details_driver_fkey', 'vehicle_details', type_='foreignkey')
    op.create_foreign_key(None, 'vehicle_details', 'driver', ['driver_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('vehicle_details', 'driver')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_details', sa.Column('driver', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'vehicle_details', type_='foreignkey')
    op.create_foreign_key('vehicle_details_driver_fkey', 'vehicle_details', 'driver', ['driver'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('vehicle_details', 'driver_id')
    op.add_column('policy_extension', sa.Column('ic_extension', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'policy_extension', type_='foreignkey')
    op.create_foreign_key('policy_extension_ic_extension_fkey', 'policy_extension', 'ic_extension', ['ic_extension'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('policy_extension', 'ic_extension_id')
    op.add_column('policy_benefits', sa.Column('ic_benefit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'policy_benefits', type_='foreignkey')
    op.create_foreign_key('policy_benefits_ic_benefit_fkey', 'policy_benefits', 'ic_benefit', ['ic_benefit'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('policy_benefits', 'ic_benefit_id')
    op.drop_constraint(None, 'master_policy', type_='foreignkey')
    op.create_foreign_key('master_policy_company_fkey', 'master_policy', 'company_details', ['company'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('ic_extension', sa.Column('extension', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ic_extension', sa.Column('insurance_company', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ic_extension', type_='foreignkey')
    op.drop_constraint(None, 'ic_extension', type_='foreignkey')
    op.create_foreign_key('ic_extension_insurance_company_fkey', 'ic_extension', 'insurance_company', ['insurance_company'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('ic_extension_extension_fkey', 'ic_extension', 'extension', ['extension'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('ic_extension', 'insurance_company_id')
    op.drop_column('ic_extension', 'extension_id')
    op.add_column('ic_benefit', sa.Column('benefit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ic_benefit', sa.Column('insurance_company', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ic_benefit', type_='foreignkey')
    op.drop_constraint(None, 'ic_benefit', type_='foreignkey')
    op.create_foreign_key('ic_benefit_insurance_company_fkey', 'ic_benefit', 'insurance_company', ['insurance_company'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('ic_benefit_benefit_fkey', 'ic_benefit', 'benefit', ['benefit'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('ic_benefit', 'insurance_company_id')
    op.drop_column('ic_benefit', 'benefit_id')
    op.drop_table('ic_rate_discount')
    # ### end Alembic commands ###
