"""empty message

Revision ID: 5dc36dc922fb
Revises: 766ff092aaf8
Create Date: 2019-09-21 10:37:30.145514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dc36dc922fb'
down_revision = '766ff092aaf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ic_rate_discount')
    op.add_column('constituency', sa.Column('county_id', sa.Integer(), nullable=True))
    op.drop_constraint('constituency_county_fkey', 'constituency', type_='foreignkey')
    op.create_foreign_key(None, 'constituency', 'county', ['county_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('constituency', 'county')
    op.add_column('insurance_company', sa.Column('ncd_rate', sa.Float(), nullable=True))
    op.add_column('ward', sa.Column('constituency_id', sa.Integer(), nullable=True))
    op.add_column('ward', sa.Column('county_id', sa.Integer(), nullable=True))
    op.drop_constraint('ward_constituency_fkey', 'ward', type_='foreignkey')
    op.drop_constraint('ward_county_fkey', 'ward', type_='foreignkey')
    op.create_foreign_key(None, 'ward', 'constituency', ['constituency_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'ward', 'county', ['county_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('ward', 'constituency')
    op.drop_column('ward', 'county')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ward', sa.Column('county', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ward', sa.Column('constituency', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ward', type_='foreignkey')
    op.drop_constraint(None, 'ward', type_='foreignkey')
    op.create_foreign_key('ward_county_fkey', 'ward', 'county', ['county'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('ward_constituency_fkey', 'ward', 'constituency', ['constituency'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('ward', 'county_id')
    op.drop_column('ward', 'constituency_id')
    op.drop_column('insurance_company', 'ncd_rate')
    op.add_column('constituency', sa.Column('county', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'constituency', type_='foreignkey')
    op.create_foreign_key('constituency_county_fkey', 'constituency', 'county', ['county'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('constituency', 'county_id')
    op.create_table('ic_rate_discount',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ic_company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rates', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ic_company_id'], ['insurance_company.id'], name='ic_rate_discount_ic_company_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='ic_rate_discount_pkey')
    )
    # ### end Alembic commands ###
