"""empty message

Revision ID: 601d6f935c53
Revises: 26e7cd51eb66
Create Date: 2019-09-23 11:41:13.363780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '601d6f935c53'
down_revision = '26e7cd51eb66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ic_loadings', sa.Column('loading_id', sa.Integer(), nullable=True))
    op.drop_constraint('ic_loadings_loading_fkey', 'ic_loadings', type_='foreignkey')
    op.create_foreign_key(None, 'ic_loadings', 'loading', ['loading_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('ic_loadings', 'loading')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ic_loadings', sa.Column('loading', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ic_loadings', type_='foreignkey')
    op.create_foreign_key('ic_loadings_loading_fkey', 'ic_loadings', 'loading', ['loading'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('ic_loadings', 'loading_id')
    # ### end Alembic commands ###
