"""empty message

Revision ID: 60c6e3c41a1b
Revises: f03ee77e61b0
Create Date: 2019-08-29 15:12:32.536776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60c6e3c41a1b'
down_revision = 'f03ee77e61b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insurance_subclass', sa.Column('acronym', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insurance_subclass', 'acronym')
    # ### end Alembic commands ###
