"""empty message

Revision ID: 62ba9e634f85
Revises: 5dc36dc922fb
Create Date: 2019-09-21 12:54:33.485502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62ba9e634f85'
down_revision = '5dc36dc922fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('country', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'country')
    # ### end Alembic commands ###
