"""empty message

Revision ID: 668264d9f023
Revises: 
Create Date: 2019-09-12 10:37:01.971927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '668264d9f023'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ic_rate_discount',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ic_company_id', sa.Integer(), nullable=True),
    sa.Column('rates', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ic_company_id'], ['insurance_company.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ic_benefit', sa.Column('benefit_id', sa.Integer(), nullable=True))
    op.add_column('ic_benefit', sa.Column('insurance_company_id', sa.Integer(), nullable=True))
    op.drop_constraint('ic_benefit_benefit_fkey', 'ic_benefit', type_='foreignkey')
    op.drop_constraint('ic_benefit_insurance_company_fkey', 'ic_benefit', type_='foreignkey')
    op.create_foreign_key(None, 'ic_benefit', 'insurance_company', ['insurance_company_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'ic_benefit', 'benefit', ['benefit_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('ic_benefit', 'benefit')
    op.drop_column('ic_benefit', 'insurance_company')
    op.add_column('ic_extension', sa.Column('extension_id', sa.Integer(), nullable=True))
    op.add_column('ic_extension', sa.Column('insurance_company_id', sa.Integer(), nullable=True))
    op.drop_constraint('ic_extension_extension_fkey', 'ic_extension', type_='foreignkey')
    op.drop_constraint('ic_extension_insurance_company_fkey', 'ic_extension', type_='foreignkey')
    op.create_foreign_key(None, 'ic_extension', 'extension', ['extension_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'ic_extension', 'insurance_company', ['insurance_company_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('ic_extension', 'insurance_company')
    op.drop_column('ic_extension', 'extension')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ic_extension', sa.Column('extension', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ic_extension', sa.Column('insurance_company', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ic_extension', type_='foreignkey')
    op.drop_constraint(None, 'ic_extension', type_='foreignkey')
    op.create_foreign_key('ic_extension_insurance_company_fkey', 'ic_extension', 'insurance_company', ['insurance_company'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('ic_extension_extension_fkey', 'ic_extension', 'extension', ['extension'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('ic_extension', 'insurance_company_id')
    op.drop_column('ic_extension', 'extension_id')
    op.add_column('ic_benefit', sa.Column('insurance_company', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ic_benefit', sa.Column('benefit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ic_benefit', type_='foreignkey')
    op.drop_constraint(None, 'ic_benefit', type_='foreignkey')
    op.create_foreign_key('ic_benefit_insurance_company_fkey', 'ic_benefit', 'insurance_company', ['insurance_company'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('ic_benefit_benefit_fkey', 'ic_benefit', 'benefit', ['benefit'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('ic_benefit', 'insurance_company_id')
    op.drop_column('ic_benefit', 'benefit_id')
    op.drop_table('ic_rate_discount')
    # ### end Alembic commands ###
