"""empty message

Revision ID: 67c3dfb9c806
Revises: 26892502c566
Create Date: 2019-09-11 12:10:44.547137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67c3dfb9c806'
down_revision = '26892502c566'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ic_rate_discount',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ic_company_id', sa.Integer(), nullable=True),
    sa.Column('rates', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ic_company_id'], ['insurance_company.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ic_rate_discount')
    # ### end Alembic commands ###
