"""Updated the company details/insurance_company relationship

Revision ID: 703322fc0fce
Revises: 50f03fbd58b9
Create Date: 2019-09-10 16:03:48.651139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '703322fc0fce'
down_revision = '50f03fbd58b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('child_policy_company_fkey', 'child_policy', type_='foreignkey')
    op.create_foreign_key(None, 'child_policy', 'insurance_company', ['company'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'child_policy', type_='foreignkey')
    op.create_foreign_key('child_policy_company_fkey', 'child_policy', 'company_details', ['company'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
