"""empty message

Revision ID: 70c569483518
Revises: 49e409e2794d
Create Date: 2019-09-20 12:14:35.462688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70c569483518'
down_revision = '49e409e2794d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('country', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'country')
    # ### end Alembic commands ###
