"""empty message

Revision ID: 71da5867b336
Revises: 3beaa70895fe
Create Date: 2019-07-30 13:47:39.868621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71da5867b336'
down_revision = '3beaa70895fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('broker', 'mpesa_paybill',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('broker', 'mpesa_paybill',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
