"""empty message

Revision ID: 766ff092aaf8
Revises: 70c569483518
Create Date: 2019-09-21 10:29:49.062631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '766ff092aaf8'
down_revision = '70c569483518'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ic_rate_discount')
    op.add_column('insurance_company', sa.Column('ncd_rate', sa.Float(), nullable=True))
    op.drop_column('user_profile', 'country')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('country', sa.VARCHAR(length=3), autoincrement=False, nullable=True))
    op.drop_column('insurance_company', 'ncd_rate')
    op.create_table('ic_rate_discount',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ic_company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rates', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ic_company_id'], ['insurance_company.id'], name='ic_rate_discount_ic_company_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='ic_rate_discount_pkey')
    )
    # ### end Alembic commands ###
