"""empty message

Revision ID: 81c0162493d3
Revises: ca7d8712c721
Create Date: 2019-09-26 17:32:24.127556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81c0162493d3'
down_revision = 'ca7d8712c721'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_customer', sa.Column('org_reg_number', sa.String(length=50), nullable=True))
    op.drop_column('organization_customer', 'org_registration_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_customer', sa.Column('org_registration_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('organization_customer', 'org_reg_number')
    # ### end Alembic commands ###
