"""empty message

Revision ID: 89a938ea3d31
Revises: 50f03fbd58b9
Create Date: 2019-08-29 16:17:13.701486

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '89a938ea3d31'
down_revision = '50f03fbd58b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('age_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data', sa.Integer(), nullable=False),
    sa.Column('lower_limit', sa.Integer(), nullable=False),
    sa.Column('upper_limit', sa.Integer(), nullable=False),
    sa.Column('relativity', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('make_origin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make_origin', sa.String(length=100), nullable=False),
    sa.Column('relativity', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sum_insured_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lower_limit', sa.Integer(), nullable=False),
    sa.Column('upper_limit', sa.Integer(), nullable=False),
    sa.Column('relativity', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('licence_classes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company', sa.Integer(), nullable=True),
    sa.Column('insurance_class', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company'], ['company_details.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['insurance_class'], ['insurance_class.class_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('constituency', sa.Integer(), nullable=True),
    sa.Column('ward', sa.Integer(), nullable=True),
    sa.Column('relativity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['constituency'], ['constituency.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ward'], ['ward.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('licenced_classes')
    op.alter_column('child_policy', 'rate',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_constraint('child_policy_company_fkey', 'child_policy', type_='foreignkey')
    op.create_foreign_key(None, 'child_policy', 'company_details', ['company'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('insurance_company', sa.Column('associated_company', sa.Integer(), nullable=True))
    op.drop_constraint('insurance_company_company_details_fkey', 'insurance_company', type_='foreignkey')
    op.create_foreign_key(None, 'insurance_company', 'company_details', ['associated_company'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('insurance_company', 'company_details')
    op.add_column('insurance_subclass', sa.Column('acronym', sa.String(length=50), nullable=True))
    op.drop_constraint('master_policy_company_fkey', 'master_policy', type_='foreignkey')
    op.create_foreign_key(None, 'master_policy', 'company_details', ['company'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'master_policy', type_='foreignkey')
    op.create_foreign_key('master_policy_company_fkey', 'master_policy', 'insurance_company', ['company'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('insurance_subclass', 'acronym')
    op.add_column('insurance_company', sa.Column('company_details', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'insurance_company', type_='foreignkey')
    op.create_foreign_key('insurance_company_company_details_fkey', 'insurance_company', 'company_details', ['company_details'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('insurance_company', 'associated_company')
    op.drop_constraint(None, 'child_policy', type_='foreignkey')
    op.create_foreign_key('child_policy_company_fkey', 'child_policy', 'insurance_company', ['company'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('child_policy', 'rate',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_table('licenced_classes',
    sa.Column('company', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('class', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['class'], ['insurance_class.class_id'], name='licenced_classes_class_fkey'),
    sa.ForeignKeyConstraint(['company'], ['company_details.id'], name='licenced_classes_company_fkey')
    )
    op.drop_table('location_data')
    op.drop_table('licence_classes')
    op.drop_table('sum_insured_rates')
    op.drop_table('make_origin')
    op.drop_table('age_data')
    # ### end Alembic commands ###
