"""empty message

Revision ID: 921b10cba46d
Revises: b90a7ee6466d
Create Date: 2019-08-09 13:05:26.939922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '921b10cba46d'
down_revision = 'b90a7ee6466d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('company_details_avatar_key', 'company_details', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('company_details_avatar_key', 'company_details', ['avatar'])
    # ### end Alembic commands ###
