"""empty message

Revision ID: 93669568ff6d
Revises: 3b2a6219957b
Create Date: 2019-08-05 15:59:47.264770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93669568ff6d'
down_revision = '3b2a6219957b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ia_customer_customer_number_key', 'ia_customer', type_='unique')
    op.drop_column('individual_customer', 'customer_number')
    op.add_column('organization_customer', sa.Column('postal_address', sa.String(length=100), nullable=True))
    op.drop_constraint('ta_customer_customer_number_key', 'ta_customer', type_='unique')
    op.add_column('user_profile', sa.Column('postal_address', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'postal_address')
    op.create_unique_constraint('ta_customer_customer_number_key', 'ta_customer', ['customer_number'])
    op.drop_column('organization_customer', 'postal_address')
    op.add_column('individual_customer', sa.Column('customer_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_unique_constraint('ia_customer_customer_number_key', 'ia_customer', ['customer_number'])
    # ### end Alembic commands ###
