"""empty message

Revision ID: 961a9c02a4b7
Revises: f305fdd4f08f
Create Date: 2019-12-28 11:11:56.186158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '961a9c02a4b7'
down_revision = 'f305fdd4f08f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('individual_customer', sa.Column('email_2', sa.String(length=100), nullable=True))
    op.add_column('individual_customer', sa.Column('phone_2', sa.BIGINT(), nullable=True))
    op.create_unique_constraint(None, 'individual_customer', ['email_2'])
    op.create_unique_constraint(None, 'individual_customer', ['phone_2'])
    op.add_column('organization_customer', sa.Column('email_2', sa.String(length=100), nullable=True))
    op.add_column('organization_customer', sa.Column('phone_2', sa.BIGINT(), nullable=True))
    op.create_unique_constraint(None, 'organization_customer', ['email_2'])
    op.create_unique_constraint(None, 'organization_customer', ['phone_2'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organization_customer', type_='unique')
    op.drop_constraint(None, 'organization_customer', type_='unique')
    op.drop_column('organization_customer', 'phone_2')
    op.drop_column('organization_customer', 'email_2')
    op.drop_constraint(None, 'individual_customer', type_='unique')
    op.drop_constraint(None, 'individual_customer', type_='unique')
    op.drop_column('individual_customer', 'phone_2')
    op.drop_column('individual_customer', 'email_2')
    # ### end Alembic commands ###
