"""empty message

Revision ID: 9d181d0896d9
Revises: 961a9c02a4b7
Create Date: 2019-12-29 22:51:34.839195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d181d0896d9'
down_revision = '961a9c02a4b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('individual_customer_email_2_key', 'individual_customer', type_='unique')
    op.drop_constraint('individual_customer_phone_2_key', 'individual_customer', type_='unique')
    op.drop_column('individual_customer', 'email_2')
    op.drop_column('individual_customer', 'phone_2')
    op.add_column('user_profile', sa.Column('email_2', sa.String(length=100), nullable=True))
    op.add_column('user_profile', sa.Column('phone_2', sa.BIGINT(), nullable=True))
    op.create_unique_constraint(None, 'user_profile', ['phone_2'])
    op.create_unique_constraint(None, 'user_profile', ['email_2'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profile', type_='unique')
    op.drop_constraint(None, 'user_profile', type_='unique')
    op.drop_column('user_profile', 'phone_2')
    op.drop_column('user_profile', 'email_2')
    op.add_column('individual_customer', sa.Column('phone_2', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('individual_customer', sa.Column('email_2', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_unique_constraint('individual_customer_phone_2_key', 'individual_customer', ['phone_2'])
    op.create_unique_constraint('individual_customer_email_2_key', 'individual_customer', ['email_2'])
    # ### end Alembic commands ###
