"""empty message

Revision ID: a4be040d1fdc
Revises: ac29d5f395a8
Create Date: 2019-09-10 15:32:35.672387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4be040d1fdc'
down_revision = 'ac29d5f395a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('child_policy_company_fkey', 'child_policy', type_='foreignkey')
    op.create_foreign_key(None, 'child_policy', 'insurance_company', ['company'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'child_policy', type_='foreignkey')
    op.create_foreign_key('child_policy_company_fkey', 'child_policy', 'company_details', ['company'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
