"""empty message

Revision ID: ac29d5f395a8
Revises: c3f7461ebdb9
Create Date: 2019-09-10 15:18:12.121106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac29d5f395a8'
down_revision = 'c3f7461ebdb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ic_benefit', sa.Column('benefit_id', sa.Integer(), nullable=True))
    op.drop_constraint('ic_benefit_benefit_fkey', 'ic_benefit', type_='foreignkey')
    op.create_foreign_key(None, 'ic_benefit', 'benefit', ['benefit_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('ic_benefit', 'benefit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ic_benefit', sa.Column('benefit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ic_benefit', type_='foreignkey')
    op.create_foreign_key('ic_benefit_benefit_fkey', 'ic_benefit', 'benefit', ['benefit'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('ic_benefit', 'benefit_id')
    # ### end Alembic commands ###
