"""empty message

Revision ID: cc75dc4f6365
Revises: 74ee89158e8c
Create Date: 2019-07-26 12:19:23.851873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc75dc4f6365'
down_revision = '74ee89158e8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('insurance_subclass_name_key', 'insurance_subclass', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('insurance_subclass_name_key', 'insurance_subclass', ['name'])
    # ### end Alembic commands ###
