"""empty message

Revision ID: cc8d9de23337
Revises: d416f087e0b4
Create Date: 2019-10-04 16:44:02.929558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc8d9de23337'
down_revision = 'd416f087e0b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('child_policy', 'reason')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('child_policy', sa.Column('reason', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
