"""empty message

Revision ID: cd6832e7116f
Revises: d769f242267e
Create Date: 2019-09-12 17:24:03.083304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd6832e7116f'
down_revision = 'd769f242267e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_details', sa.Column('driver_id', sa.Integer(), nullable=True))
    op.drop_constraint('vehicle_details_driver_fkey', 'vehicle_details', type_='foreignkey')
    op.create_foreign_key(None, 'vehicle_details', 'driver', ['driver_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('vehicle_details', 'driver')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_details', sa.Column('driver', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'vehicle_details', type_='foreignkey')
    op.create_foreign_key('vehicle_details_driver_fkey', 'vehicle_details', 'driver', ['driver'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('vehicle_details', 'driver_id')
    # ### end Alembic commands ###
