"""empty message

Revision ID: d416f087e0b4
Revises: 1aae715e7889
Create Date: 2019-09-30 13:41:24.947467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd416f087e0b4'
down_revision = '1aae715e7889'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('child_policy', sa.Column('reason', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('child_policy', 'reason')
    # ### end Alembic commands ###
