"""empty message

Revision ID: d769f242267e
Revises: 668264d9f023
Create Date: 2019-09-12 13:57:41.105748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd769f242267e'
down_revision = '668264d9f023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('master_policy_company_fkey', 'master_policy', type_='foreignkey')
    op.create_foreign_key(None, 'master_policy', 'insurance_company', ['company'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'master_policy', type_='foreignkey')
    op.create_foreign_key('master_policy_company_fkey', 'master_policy', 'company_details', ['company'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
