"""empty message

Revision ID: da4dccdf63ea
Revises: 2c1a84553120
Create Date: 2019-09-04 14:17:34.978567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da4dccdf63ea'
down_revision = '2c1a84553120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('child_policy', sa.Column('subclass', sa.String(length=22), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('child_policy', 'subclass')
    # ### end Alembic commands ###
