"""empty message

Revision ID: de4bf6718891
Revises: 74d1324ca34c
Create Date: 2019-09-26 12:12:30.079063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de4bf6718891'
down_revision = '74d1324ca34c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('independent_agent', sa.Column('ira_license_number', sa.String(length=15), nullable=True))
    op.add_column('independent_agent', sa.Column('website', sa.String(length=150), nullable=True))
    op.create_unique_constraint(None, 'independent_agent', ['website'])
    op.drop_column('independent_agent', 'ira_licence_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('independent_agent', sa.Column('ira_licence_number', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'independent_agent', type_='unique')
    op.drop_column('independent_agent', 'website')
    op.drop_column('independent_agent', 'ira_license_number')
    # ### end Alembic commands ###
