"""empty message

Revision ID: e4f037896fa4
Revises: 70c569483518
Create Date: 2019-09-23 20:28:48.390697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4f037896fa4'
down_revision = '70c569483518'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ic_loadings', sa.Column('insurance_company_id', sa.Integer(), nullable=True))
    op.add_column('ic_loadings', sa.Column('loading_id', sa.Integer(), nullable=True))
    op.drop_constraint('ic_loadings_insurance_company_fkey', 'ic_loadings', type_='foreignkey')
    op.drop_constraint('ic_loadings_loading_fkey', 'ic_loadings', type_='foreignkey')
    op.create_foreign_key(None, 'ic_loadings', 'loading', ['loading_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'ic_loadings', 'insurance_company', ['insurance_company_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('ic_loadings', 'loading')
    op.drop_column('ic_loadings', 'insurance_company')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ic_loadings', sa.Column('insurance_company', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ic_loadings', sa.Column('loading', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ic_loadings', type_='foreignkey')
    op.drop_constraint(None, 'ic_loadings', type_='foreignkey')
    op.create_foreign_key('ic_loadings_loading_fkey', 'ic_loadings', 'loading', ['loading'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('ic_loadings_insurance_company_fkey', 'ic_loadings', 'insurance_company', ['insurance_company'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('ic_loadings', 'loading_id')
    op.drop_column('ic_loadings', 'insurance_company_id')
    # ### end Alembic commands ###
