"""empty message

Revision ID: e4fd3c91d8ab
Revises: 2b3012611279
Create Date: 2019-08-24 16:09:19.775228

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e4fd3c91d8ab'
down_revision = '2b3012611279'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('child_policy', sa.Column('company', sa.Integer(), nullable=True))
    op.add_column('child_policy', sa.Column('cp_number', sa.String(length=22), nullable=False))
    op.add_column('child_policy', sa.Column('pricing_model', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'child_policy', ['cp_number'])
    op.create_foreign_key(None, 'child_policy', 'insurance_company', ['company'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('insurance_company', 'company_phone',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.add_column('policy_benefits', sa.Column('amount', sa.Float(), nullable=False))
    op.drop_column('policy_benefits', 'limit')
    op.drop_column('policy_benefits', 'premium')
    op.add_column('policy_extensions', sa.Column('amount', sa.Float(), nullable=False))
    op.drop_column('policy_extensions', 'limit')
    op.drop_column('policy_extensions', 'premium')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policy_extensions', sa.Column('premium', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('policy_extensions', sa.Column('limit', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('policy_extensions', 'amount')
    op.add_column('policy_benefits', sa.Column('premium', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('policy_benefits', sa.Column('limit', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('policy_benefits', 'amount')
    op.alter_column('insurance_company', 'company_phone',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint(None, 'child_policy', type_='foreignkey')
    op.drop_constraint(None, 'child_policy', type_='unique')
    op.drop_column('child_policy', 'pricing_model')
    op.drop_column('child_policy', 'cp_number')
    op.drop_column('child_policy', 'company')
    # ### end Alembic commands ###
