"""empty message

Revision ID: ee7339d2f879
Revises: a4be040d1fdc
Create Date: 2019-09-10 16:36:32.633673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee7339d2f879'
down_revision = 'a4be040d1fdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ic_extension', sa.Column('extension_id', sa.Integer(), nullable=True))
    op.drop_constraint('ic_extension_extension_fkey', 'ic_extension', type_='foreignkey')
    op.create_foreign_key(None, 'ic_extension', 'extension', ['extension_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('ic_extension', 'extension')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ic_extension', sa.Column('extension', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ic_extension', type_='foreignkey')
    op.create_foreign_key('ic_extension_extension_fkey', 'ic_extension', 'extension', ['extension'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('ic_extension', 'extension_id')
    # ### end Alembic commands ###
