"""empty message

Revision ID: f03ee77e61b0
Revises: 4fe3abff50a6
Create Date: 2019-08-29 13:32:46.695664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f03ee77e61b0'
down_revision = '4fe3abff50a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sum_insured_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lower_limit', sa.Integer(), nullable=False),
    sa.Column('upper_limit', sa.Integer(), nullable=False),
    sa.Column('relativity', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sum_insured_rates')
    # ### end Alembic commands ###
