"""empty message

Revision ID: f305fdd4f08f
Revises: 5554722a05c3
Create Date: 2019-12-16 15:55:24.539711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f305fdd4f08f'
down_revision = '5554722a05c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('broker_website_key', 'broker', type_='unique')
    op.drop_constraint('independent_agent_website_key', 'independent_agent', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('independent_agent_website_key', 'independent_agent', ['website'])
    op.create_unique_constraint('broker_website_key', 'broker', ['website'])
    # ### end Alembic commands ###
