"""empty message

Revision ID: f3d478a32225
Revises: 
Create Date: 2019-09-12 19:46:00.326311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3d478a32225'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policy_benefits', sa.Column('ic_benefit_id', sa.Integer(), nullable=True))
    op.drop_constraint('policy_benefits_ic_benefit_fkey', 'policy_benefits', type_='foreignkey')
    op.create_foreign_key(None, 'policy_benefits', 'ic_benefit', ['ic_benefit_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('policy_benefits', 'ic_benefit')
    op.add_column('policy_extension', sa.Column('ic_extension_id', sa.Integer(), nullable=True))
    op.drop_constraint('policy_extension_ic_extension_fkey', 'policy_extension', type_='foreignkey')
    op.create_foreign_key(None, 'policy_extension', 'ic_extension', ['ic_extension_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('policy_extension', 'ic_extension')
    op.add_column('vehicle_details', sa.Column('driver_id', sa.Integer(), nullable=True))
    op.drop_constraint('vehicle_details_driver_fkey', 'vehicle_details', type_='foreignkey')
    op.create_foreign_key(None, 'vehicle_details', 'driver', ['driver_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('vehicle_details', 'driver')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_details', sa.Column('driver', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'vehicle_details', type_='foreignkey')
    op.create_foreign_key('vehicle_details_driver_fkey', 'vehicle_details', 'driver', ['driver'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('vehicle_details', 'driver_id')
    op.add_column('policy_extension', sa.Column('ic_extension', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'policy_extension', type_='foreignkey')
    op.create_foreign_key('policy_extension_ic_extension_fkey', 'policy_extension', 'ic_extension', ['ic_extension'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('policy_extension', 'ic_extension_id')
    op.add_column('policy_benefits', sa.Column('ic_benefit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'policy_benefits', type_='foreignkey')
    op.create_foreign_key('policy_benefits_ic_benefit_fkey', 'policy_benefits', 'ic_benefit', ['ic_benefit'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('policy_benefits', 'ic_benefit_id')
    # ### end Alembic commands ###
