"""empty message

Revision ID: fb10c3dde23e
Revises: 24d54c879749
Create Date: 2019-08-28 16:25:59.187296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb10c3dde23e'
down_revision = '24d54c879749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('child_policy_company_fkey', 'child_policy', type_='foreignkey')
    op.create_foreign_key(None, 'child_policy', 'company_details', ['company'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'child_policy', type_='foreignkey')
    op.create_foreign_key('child_policy_company_fkey', 'child_policy', 'insurance_company', ['company'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
