"""empty message

Revision ID: fc5213b3d896
Revises: 9b9374ba6fba
Create Date: 2019-08-22 09:06:51.079946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc5213b3d896'
down_revision = '9b9374ba6fba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('child_policy', sa.Column('date_activated', sa.DateTime(), nullable=True))
    op.add_column('child_policy', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('individual_customer', sa.Column('customer_number', sa.String(length=50), nullable=True))
    op.add_column('organization_customer', sa.Column('customer_number', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_customer', 'customer_number')
    op.drop_column('individual_customer', 'customer_number')
    op.drop_column('child_policy', 'is_active')
    op.drop_column('child_policy', 'date_activated')
    # ### end Alembic commands ###
